# Generated by Django 4.0.2 on 2022-02-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Author_1',
        ),
    ]
