# Generated by Django 4.0.2 on 2022-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_rename_author_author_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('goes_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
