# Generated by Django 4.0.2 on 2022-02-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_blog_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Coment',
        ),
    ]
